from pathlib import Path

p=Path('tools/v101_patch.py')
s=p.read_text(encoding='utf-8')
old="async ensurePaymentLedger(){let created=0;for(const s of this.services){let paid=Number(s.paidValue||0);if(paid<=0)continue;let existing=this.payments.filter(p=>Number(p.serviceId)===Number(s.id));if(existing.length)continue;let rs=this.receipts.filter(r=>Number(r.serviceId)===Number(s.id)).sort((a,b)=>Number(a.id||0)-Number(b.id||0)),known=0;for(const r of rs){let amount=Number(r.total||0);if(amount<=0)continue;await db.payments.add({serviceId:s.id,providerId:s.providerId,date:r.paymentDate||r.date||s.paymentDate||s.serviceDate||this.today(),amount,method:r.paymentMethod||s.paymentMethod||'Não informado',receiptId:r.id,source:'receipt-migration',createdAt:new Date().toISOString()});known+=amount;created++}let residual=Math.max(0,paid-known);if(residual>0.009){await db.payments.add({serviceId:s.id,providerId:s.providerId,date:s.paymentDate||s.serviceDate||this.today(),amount:residual,method:s.paymentMethod||'Não informado',receiptId:null,source:'service-migration',createdAt:new Date().toISOString()});created++}}if(created){await db.meta.put({key:'paymentsLedgerV1',value:{created,at:new Date().toISOString()}});console.info('[ReciboCondo] Histórico de pagamentos reconstruído:',created)}return created}"
new="async ensurePaymentLedger(){let created=0;for(const s of this.services){let paid=Number(s.paidValue||0);if(paid<=0)continue;await db.transaction('rw',db.payments,async()=>{let existing=await db.payments.where('serviceId').equals(s.id).toArray();if(existing.length)return;let rows=[],rs=this.receipts.filter(r=>Number(r.serviceId)===Number(s.id)).sort((a,b)=>Number(a.id||0)-Number(b.id||0)),known=0;for(const r of rs){let amount=Number(r.total||0);if(amount<=0)continue;rows.push({serviceId:s.id,providerId:s.providerId,date:r.paymentDate||r.date||s.paymentDate||s.serviceDate||this.today(),amount,method:r.paymentMethod||s.paymentMethod||'Não informado',receiptId:r.id,source:'receipt-migration',createdAt:new Date().toISOString()});known+=amount}let residual=Math.max(0,paid-known);if(residual>0.009)rows.push({serviceId:s.id,providerId:s.providerId,date:s.paymentDate||s.serviceDate||this.today(),amount:residual,method:s.paymentMethod||'Não informado',receiptId:null,source:'service-migration',createdAt:new Date().toISOString()});if(rows.length){await db.payments.bulkAdd(rows);created+=rows.length}})}if(created){await db.meta.put({key:'paymentsLedgerV1',value:{created,at:new Date().toISOString()}});console.info('[ReciboCondo] Histórico de pagamentos reconstruído:',created)}return created}"
if s.count(old)!=1:
    raise SystemExit(f'expected one original migration block, got {s.count(old)}')
p.write_text(s.replace(old,new,1),encoding='utf-8')
print('v101 migration hardened: atomic per service')
